version: '3.1'

networks:
  alfresco:

volumes:
  alfresco-data:
  postgres-data:
  solr6-data:

services:
  alfresco:
    build: .
    networks:
      alfresco:
        aliases:
          - alfresco
    volumes:
      - alfresco-data:/data      
    ports:
      - 8082:8080
    environment:
      LANG: en_US.utf8
      JAVA_OPTS: "
                    -Dalfresco.home=/usr/local/tomcat
                    -Dfile.encoding=UTF-8
                    -XX:ReservedCodeCacheSize=128m
                    -Xms2048M -Xmx2048M
                    -Ddir.root=/data
                    -Ddb.driver=org.postgresql.Driver
                    -Ddb.username=alfresco
                    -Ddb.password=alfresco
                    -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                    -Dsolr.host=solr6
                    -Dsolr.port=8983
                    -Dsolr.secureComms=none
                    -Dsolr.base.url=/solr
                    -Dindex.subsystem.name=solr6
                    -Dalfresco-pdf-renderer.url=http://alfresco-pdf-renderer:8090/
                    -Djodconverter.url=http://libreoffice:8090/
                    -Dimg.url=http://imagemagick:8090/
                  "
  share:
    image: alfresco/alfresco-share:6.0.a
    networks:
      alfresco:
        aliases:
          - share
    environment:
        - REPO_HOST=alfresco
        - REPO_PORT=8080
    ports:
        - 8080:8080

  postgres:
    image: postgres:10.1
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    networks:
      alfresco:
        aliases:
          - postgres
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco

  solr6:
    image: alfresco/alfresco-search-services:1.1.1
    volumes:
      - solr6-data:/opt/alfresco-search-services/data
    networks:
      alfresco:
        aliases:
          - solr6
    environment:
        - SOLR_ALFRESCO_HOST=alfresco
        - SOLR_ALFRESCO_PORT=8080
        - SOLR_SOLR_HOST=solr6
        - SOLR_SOLR_PORT=8983
        - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
    ports:
        - 8983:8983  

  libreoffice:
   image: alfresco/alfresco-libreoffice:latest
   networks:
    alfresco:
      aliases:
        - libreoffice
  
  imagemagick:
   image: alfresco/alfresco-imagemagick:latest
   networks:
    alfresco:
      aliases:
        - imagemagick

  alfresco-pdf-renderer:
   image: alfresco/alfresco-pdf-renderer:latest
   networks:
    alfresco:
      aliases:
        - alfresco-pdf-renderer
