version: '3.1'

networks:
  appNet:

services:
 alfresco:
  build: ./alfresco
  networks:
   dphNet:
    aliases:
      - alfresco
  ports:
   - 8080:8080
   - 9999:9999
  environment:
   - LANG=en_US.utf8

 share:
  build: ./share
  ports:
   - 9090:8080 

 db:
  build: ./postgres
  environment:
   - POSTGRES_DB=alfresco
   - POSTGRES_USER=alfresco
   - POSTGRES_PASSWORD=alfresco
  networks:
   dphNet:
    aliases:
      - db

 solr6:
  image: keensoft/alfresco-solr6:201707-GA
  networks:
   dphNet:
    aliases:
      - solr6

 libreoffice:
  image: keensoft/libreoffice:latest
  networks:
   dphNet:
    aliases:
      - libreoffice
