version: '3.1'

networks:
  appNet:

services:
 alfresco:
  build: ./alfresco
  networks:
   dphNet:
    aliases:
      - alfresco
  ports:
   - 9999:9999
  environment:
   - LANG=en_US.utf8

 share:
  build: ./share
  ports:
   - 8080:8080

 nginx:
  build: ./nginx
  networks:
   dphNet:
    aliases:
      - nginx
  ports: 
   - 80:80
   - 443:443

 db:
  build: ./postgres
  environment:
   - POSTGRES_DB=alfresco
   - POSTGRES_USER=alfresco
   - POSTGRES_PASSWORD=alfresco

 solr6:
  image: keensoft/alfresco-solr6:201707-GA
  ports:
   - 8100:8100

 libreoffice:
  image: keensoft/libreoffice:latest
