version: '2'
services:
 alfresco:
  build: ./alfresco
  links:
   - solr6
   - libreoffice
  ports:
   - 8080:8080
   - 9999:9999

 db:
  build: ./postgres
  network_mode: service:alfresco
  environment:
   - POSTGRES_DB=alfresco
   - POSTGRES_USER=alfresco
   - POSTGRES_PASSWORD=alfresco

 solr6:
  image: keensoft/alfresco-5.2.0-solr6
  ports:
   - 8983:8983

 libreoffice:
  image: keensoft/libreoffice:4.4.5
  user: root
